[package]
name = "feddit_archivieren"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "daemon"
path = "src/daemon.rs"

[dependencies]
daemonize = "0.5.0"
users = "0.11.0"
colored = "2.1.0"
chrono = "0.4.38"
reqwest = "0.12.4"
tokio = "1.37.0"
